name: First Workflow
on: workflow_dispatch   #this is when workflow will be ran, also could refer to a trigger
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "All Done.  Goodbye!"
